steps:
  - label: ":arch: aur-pkgbuild-update"
    agents:
      queue: "default"
    image: "ghcr.io/carteramesh/docker/aur-builder:latest"
    env:
      AUR_PUSH_CHANGES: "1"
    plugins:
      - kubernetes:
          podTemplate: aur-builder
    commands:
      - ls -l "/home/aur_builder/.ssh/id_ed25519"
      - HOME=/home/aur_builder ./pkgbuild-update.sh
